/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

/**
 * Supported timezones in IANA format.
 *
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "supportedTimezones".
 */
export type SupportedTimezones =
  | 'Pacific/Midway'
  | 'Pacific/Niue'
  | 'Pacific/Honolulu'
  | 'Pacific/Rarotonga'
  | 'America/Anchorage'
  | 'Pacific/Gambier'
  | 'America/Los_Angeles'
  | 'America/Tijuana'
  | 'America/Denver'
  | 'America/Phoenix'
  | 'America/Chicago'
  | 'America/Guatemala'
  | 'America/New_York'
  | 'America/Bogota'
  | 'America/Caracas'
  | 'America/Santiago'
  | 'America/Buenos_Aires'
  | 'America/Sao_Paulo'
  | 'Atlantic/South_Georgia'
  | 'Atlantic/Azores'
  | 'Atlantic/Cape_Verde'
  | 'Europe/London'
  | 'Europe/Berlin'
  | 'Africa/Lagos'
  | 'Europe/Athens'
  | 'Africa/Cairo'
  | 'Europe/Moscow'
  | 'Asia/Riyadh'
  | 'Asia/Dubai'
  | 'Asia/Baku'
  | 'Asia/Karachi'
  | 'Asia/Tashkent'
  | 'Asia/Calcutta'
  | 'Asia/Dhaka'
  | 'Asia/Almaty'
  | 'Asia/Jakarta'
  | 'Asia/Bangkok'
  | 'Asia/Shanghai'
  | 'Asia/Singapore'
  | 'Asia/Tokyo'
  | 'Asia/Seoul'
  | 'Australia/Brisbane'
  | 'Australia/Sydney'
  | 'Pacific/Guam'
  | 'Pacific/Noumea'
  | 'Pacific/Auckland'
  | 'Pacific/Fiji';

export interface Config {
  auth: {
    users: UserAuthOperations;
  };
  blocks: {};
  collections: {
    users: User;
    media: Media;
    operators: Operator;
    plans: Plan;
    categories: Category;
    cities: City;
    'city-landing-pages': CityLandingPage;
    promotions: Promotion;
    'click-events': ClickEvent;
    'affiliate-links': AffiliateLink;
    'box-display-config': BoxDisplayConfig;
    pages: Page;
    reviews: Review;
    'blog-posts': BlogPost;
    'blog-categories': BlogCategory;
    'speed-stats': SpeedStat;
    'price-alerts': PriceAlert;
    comparisons: Comparison;
    'analytics-daily': AnalyticsDaily;
    'payload-kv': PayloadKv;
    'payload-locked-documents': PayloadLockedDocument;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  collectionsJoins: {};
  collectionsSelect: {
    users: UsersSelect<false> | UsersSelect<true>;
    media: MediaSelect<false> | MediaSelect<true>;
    operators: OperatorsSelect<false> | OperatorsSelect<true>;
    plans: PlansSelect<false> | PlansSelect<true>;
    categories: CategoriesSelect<false> | CategoriesSelect<true>;
    cities: CitiesSelect<false> | CitiesSelect<true>;
    'city-landing-pages': CityLandingPagesSelect<false> | CityLandingPagesSelect<true>;
    promotions: PromotionsSelect<false> | PromotionsSelect<true>;
    'click-events': ClickEventsSelect<false> | ClickEventsSelect<true>;
    'affiliate-links': AffiliateLinksSelect<false> | AffiliateLinksSelect<true>;
    'box-display-config': BoxDisplayConfigSelect<false> | BoxDisplayConfigSelect<true>;
    pages: PagesSelect<false> | PagesSelect<true>;
    reviews: ReviewsSelect<false> | ReviewsSelect<true>;
    'blog-posts': BlogPostsSelect<false> | BlogPostsSelect<true>;
    'blog-categories': BlogCategoriesSelect<false> | BlogCategoriesSelect<true>;
    'speed-stats': SpeedStatsSelect<false> | SpeedStatsSelect<true>;
    'price-alerts': PriceAlertsSelect<false> | PriceAlertsSelect<true>;
    comparisons: ComparisonsSelect<false> | ComparisonsSelect<true>;
    'analytics-daily': AnalyticsDailySelect<false> | AnalyticsDailySelect<true>;
    'payload-kv': PayloadKvSelect<false> | PayloadKvSelect<true>;
    'payload-locked-documents': PayloadLockedDocumentsSelect<false> | PayloadLockedDocumentsSelect<true>;
    'payload-preferences': PayloadPreferencesSelect<false> | PayloadPreferencesSelect<true>;
    'payload-migrations': PayloadMigrationsSelect<false> | PayloadMigrationsSelect<true>;
  };
  db: {
    defaultIDType: number;
  };
  fallbackLocale: null;
  globals: {
    'site-settings': SiteSetting;
    'comparison-config': ComparisonConfig;
    navigation: Navigation;
  };
  globalsSelect: {
    'site-settings': SiteSettingsSelect<false> | SiteSettingsSelect<true>;
    'comparison-config': ComparisonConfigSelect<false> | ComparisonConfigSelect<true>;
    navigation: NavigationSelect<false> | NavigationSelect<true>;
  };
  locale: null;
  widgets: {
    collections: CollectionsWidget;
  };
  user: User;
  jobs: {
    tasks: unknown;
    workflows: unknown;
  };
}
export interface UserAuthOperations {
  forgotPassword: {
    email: string;
    password: string;
  };
  login: {
    email: string;
    password: string;
  };
  registerFirstUser: {
    email: string;
    password: string;
  };
  unlock: {
    email: string;
    password: string;
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users".
 */
export interface User {
  id: number;
  firstName?: string | null;
  lastName?: string | null;
  role: 'admin' | 'editor' | 'viewer';
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  sessions?:
    | {
        id: string;
        createdAt?: string | null;
        expiresAt: string;
      }[]
    | null;
  password?: string | null;
  collection: 'users';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media".
 */
export interface Media {
  id: number;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  thumbnailURL?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
  focalX?: number | null;
  focalY?: number | null;
  sizes?: {
    thumbnail?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    card?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    banner?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
    og?: {
      url?: string | null;
      width?: number | null;
      height?: number | null;
      mimeType?: string | null;
      filesize?: number | null;
      filename?: string | null;
    };
  };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators".
 */
export interface Operator {
  id: number;
  name: string;
  /**
   * URL-friendly nazwa, np. "orange", "play", "upc"
   */
  slug: string;
  logo?: (number | null) | Media;
  logoDark?: (number | null) | Media;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Wyświetlany na boxach i w listach
   */
  shortDescription?: string | null;
  /**
   * Oficjalna strona operatora
   */
  website?: string | null;
  supportPhone?: string | null;
  coverageMapUrl?: string | null;
  /**
   * Średnia ocena 1-5
   */
  rating?: number | null;
  reviewCount?: number | null;
  isActive?: boolean | null;
  /**
   * Partnerzy premium są wyróżnieni na stronie (monetyzacja)
   */
  isPremiumPartner?: boolean | null;
  /**
   * Wyższy = wyżej na liście. Płatne wyższe pozycje.
   */
  priority?: number | null;
  /**
   * Dane prowizji — widoczne tylko dla admina
   */
  commission?: {
    type?: ('cpc' | 'cpl' | 'cps' | 'flat') | null;
    /**
     * CPC: PLN/klik, CPL: PLN/lead, CPS: %, Flat: PLN/mies
     */
    value?: number | null;
  };
  /**
   * Dane kontaktowe — widoczne tylko dla admina
   */
  contact?: {
    person?: string | null;
    email?: string | null;
    phone?: string | null;
    notes?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans".
 */
export interface Plan {
  id: number;
  name: string;
  /**
   * URL-friendly, np. "orange-300mb-swiatlowod"
   */
  slug: string;
  operator: number | Operator;
  category: number | Category;
  technology: 'ftth' | 'fttb' | 'hfc' | '5g' | 'lte' | 'dsl' | 'satellite';
  speeds: {
    download: number;
    upload?: number | null;
    /**
     * Minimalna gwarantowana prędkość
     */
    guaranteed?: number | null;
  };
  pricing: {
    priceMonthly: number;
    /**
     * Cena w okresie promocyjnym
     */
    pricePromo?: number | null;
    /**
     * Ile miesięcy trwa cena promocyjna
     */
    promoMonths?: number | null;
    priceAfterPromo?: number | null;
    installationFee?: number | null;
    activationFee?: number | null;
    /**
     * Auto-kalkulowany: (promo * promoMonths) + (regular * remaining) + installation
     */
    totalCost24m?: number | null;
  };
  contract: {
    months: '0' | '12' | '24' | '36';
    cancellationFee?: number | null;
    freeRouterIncluded?: boolean | null;
    routerModel?: string | null;
  };
  extras?: {
    includesTV?: boolean | null;
    tvChannels?: number | null;
    includesPhone?: boolean | null;
    includesMobile?: boolean | null;
    features?:
      | {
          feature: string;
          id?: string | null;
        }[]
      | null;
    additionalInfo?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  /**
   * Kontroluje jak oferta wygląda na stronie
   */
  display?: {
    /**
     * Tekst badge np. "Najlepsza cena", "Polecamy", "HOT"
     */
    badge?: string | null;
    badgeColor?: ('green' | 'blue' | 'red' | 'orange' | 'purple' | 'gold') | null;
    /**
     * Wyróżnione obramowanie i cień
     */
    highlightBox?: boolean | null;
    /**
     * Własny tekst przycisku, np. "Zamów teraz", "Sprawdź ofertę"
     */
    customCTA?: string | null;
    /**
     * Wyższy = wyżej na liście
     */
    sortOrder?: number | null;
  };
  /**
   * Linki afiliacyjne i przekierowania
   */
  affiliate?: {
    /**
     * Docelowy URL z parametrami śledzenia
     */
    url?: string | null;
    /**
     * Nasz ID w systemie partnera
     */
    affiliateId?: string | null;
    /**
     * Strona docelowa u operatora
     */
    landingPageUrl?: string | null;
  };
  /**
   * Oferta sponsorowana / promowana
   */
  sponsoring?: {
    isSponsored?: boolean | null;
    /**
     * "Reklama", "Promowane", "Polecane"
     */
    sponsoredLabel?: string | null;
    sponsoredFrom?: string | null;
    sponsoredUntil?: string | null;
  };
  availability?: {
    isActive?: boolean | null;
    isPromoted?: boolean | null;
    /**
     * Pozostaw puste = dostępna wszędzie
     */
    regions?: (number | City)[] | null;
    validFrom?: string | null;
    validUntil?: string | null;
  };
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories".
 */
export interface Category {
  id: number;
  name: string;
  /**
   * Auto-generowany z nazwy. Używany w URL.
   */
  slug: string;
  /**
   * Prefix używany w URL, np. "internet-swiatlowodowy", "internet-5g"
   */
  urlPrefix: string;
  /**
   * Nazwa ikony z Lucide, np. "wifi", "signal", "cable"
   */
  icon?: string | null;
  description?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  /**
   * Używany w meta description i na kartach
   */
  shortDescription?: string | null;
  /**
   * Wyższa wartość = wyżej na liście
   */
  sortOrder?: number | null;
  isActive?: boolean | null;
  seo?: {
    /**
     * Szablon: użyj {{category}} i {{city}} jako placeholdery
     */
    metaTitle?: string | null;
    /**
     * Szablon: użyj {{category}} i {{city}} jako placeholdery
     */
    metaDescription?: string | null;
    /**
     * np. "Internet światłowodowy w {{city}} - porównaj oferty"
     */
    h1Template?: string | null;
    /**
     * Szablon treści dla stron z miastem. Użyj {{city}}, {{category}}.
     */
    contentTemplate?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities".
 */
export interface City {
  id: number;
  name: string;
  /**
   * URL-friendly: "warszawa", "krakow", "bielsko-biala"
   */
  slug: string;
  voivodeship:
    | 'dolnoslaskie'
    | 'kujawsko-pomorskie'
    | 'lubelskie'
    | 'lubuskie'
    | 'lodzkie'
    | 'malopolskie'
    | 'mazowieckie'
    | 'opolskie'
    | 'podkarpackie'
    | 'podlaskie'
    | 'pomorskie'
    | 'slaskie'
    | 'swietokrzyskie'
    | 'warminsko-mazurskie'
    | 'wielkopolskie'
    | 'zachodniopomorskie';
  /**
   * Do priorytetyzacji w listach i sitemap
   */
  population?: number | null;
  /**
   * Miasto wojewódzkie / duże — wyżej w listach
   */
  isMainCity?: boolean | null;
  /**
   * Operatorzy z ofertami w tym mieście
   */
  availableOperators?: (number | Operator)[] | null;
  /**
   * Na przyszłość — mapa zasięgu
   */
  coordinates?: {
    lat?: number | null;
    lng?: number | null;
  };
  isActive?: boolean | null;
  seo?: {
    /**
     * Custom title, np. "Internet w Warszawie - porównaj oferty"
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-landing-pages".
 */
export interface CityLandingPage {
  id: number;
  /**
   * np. "Światłowód Warszawa" — do identyfikacji w panelu
   */
  title: string;
  city: number | City;
  /**
   * Puste = ogólna strona miasta (wszystkie kategorie)
   */
  category?: (number | null) | Category;
  /**
   * Auto-generowany z miasta + kategorii
   */
  slug?: string | null;
  content: {
    /**
     * np. "Internet światłowodowy w Warszawie - porównaj oferty 2025"
     */
    h1: string;
    /**
     * Krótki tekst pod nagłówkiem
     */
    heroText?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Unikalna treść per miasto — ważne dla SEO!
     */
    bodyContent?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    /**
     * Pytania i odpowiedzi — wyświetlane jako FAQ Schema w Google
     */
    faqItems?:
      | {
          question: string;
          answer: {
            root: {
              type: string;
              children: {
                type: any;
                version: number;
                [k: string]: unknown;
              }[];
              direction: ('ltr' | 'rtl') | null;
              format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
              indent: number;
              version: number;
            };
            [k: string]: unknown;
          };
          id?: string | null;
        }[]
      | null;
    ctaText?: string | null;
  };
  featured?: {
    operators?: (number | Operator)[] | null;
    plans?: (number | Plan)[] | null;
    customSortOrder?:
      | {
          operator: number | Operator;
          position: number;
          id?: string | null;
        }[]
      | null;
  };
  seo?: {
    /**
     * Custom SEO title. Domyślnie generowany z szablonu kategorii.
     */
    metaTitle?: string | null;
    metaDescription?: string | null;
    /**
     * Nadpisanie canonical URL — unikanie duplikatów
     */
    canonicalUrl?: string | null;
    ogImage?: (number | null) | Media;
  };
  isActive?: boolean | null;
  publishedAt?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions".
 */
export interface Promotion {
  id: number;
  name: string;
  type: 'banner' | 'sponsored_box' | 'featured_strip' | 'popup';
  placement: 'homepage_top' | 'sidebar' | 'between_results' | 'footer' | 'category_page' | 'city_page';
  /**
   * Opcjonalnie — powiązany operator
   */
  operator?: (number | null) | Operator;
  /**
   * Opcjonalnie — powiązana oferta
   */
  plan?: (number | null) | Plan;
  image?: (number | null) | Media;
  imageMobile?: (number | null) | Media;
  title?: string | null;
  description?: string | null;
  ctaText?: string | null;
  ctaUrl?: string | null;
  /**
   * Jeśli inny niż link CTA
   */
  affiliateUrl?: string | null;
  /**
   * Hex, np. #FF6600
   */
  backgroundColor?: string | null;
  isActive?: boolean | null;
  startDate?: string | null;
  endDate?: string | null;
  /**
   * 0 = bez limitu
   */
  impressionLimit?: number | null;
  impressionCount?: number | null;
  /**
   * Wyższy = ważniejszy
   */
  priority?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events".
 */
export interface ClickEvent {
  id: number;
  plan?: (number | null) | Plan;
  operator?: (number | null) | Operator;
  promotion?: (number | null) | Promotion;
  eventType: 'click' | 'redirect' | 'impression' | 'conversion';
  sourceUrl?: string | null;
  destinationUrl?: string | null;
  userAgent?: string | null;
  /**
   * Zhashowane IP — RODO compliant
   */
  ipHash?: string | null;
  referrer?: string | null;
  utm?: {
    source?: string | null;
    medium?: string | null;
    campaign?: string | null;
    term?: string | null;
    content?: string | null;
  };
  device?: {
    type?: ('desktop' | 'mobile' | 'tablet') | null;
    browser?: string | null;
    os?: string | null;
  };
  /**
   * Z jakiej strony miasta kliknięto
   */
  city?: (number | null) | City;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-links".
 */
export interface AffiliateLink {
  id: number;
  name: string;
  operator: number | Operator;
  /**
   * np. https://partner.orange.pl/click/
   */
  baseUrl: string;
  /**
   * Nazwa parametru URL, np. "ref", "aff_id", "partner"
   */
  trackingParam?: string | null;
  /**
   * Nasz identyfikator w systemie partnera
   */
  trackingId: string;
  additionalParams?:
    | {
        key: string;
        value: string;
        id?: string | null;
      }[]
    | null;
  isActive?: boolean | null;
  cookieDays?: number | null;
  commissionType?: ('cpc' | 'cpl' | 'cps') | null;
  /**
   * PLN/klik, PLN/lead lub % od sprzedaży
   */
  commissionRate?: number | null;
  notes?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "box-display-config".
 */
export interface BoxDisplayConfig {
  id: number;
  /**
   * np. "Domyślny box", "Kompaktowy", "Szczegółowy"
   */
  name: string;
  slug: string;
  layout: 'card' | 'row' | 'compact' | 'detailed';
  /**
   * Wybierz które informacje pokazywać na boxie oferty
   */
  visibleFields?:
    | {
        fieldName:
          | 'speedDownload'
          | 'speedUpload'
          | 'priceMonthly'
          | 'pricePromo'
          | 'priceAfterPromo'
          | 'contractMonths'
          | 'totalCost24m'
          | 'installationFee'
          | 'technology'
          | 'features'
          | 'includesTV'
          | 'includesPhone'
          | 'freeRouter'
          | 'rating';
        /**
         * Custom etykieta, np. "Prędkość", "Cena/mies."
         */
        label?: string | null;
        displayOrder?: number | null;
        showOnMobile?: boolean | null;
        id?: string | null;
      }[]
    | null;
  showOperatorLogo?: boolean | null;
  showBadge?: boolean | null;
  showRating?: boolean | null;
  showSponsored?: boolean | null;
  ctaButtonText?: string | null;
  /**
   * Hex kolor, np. #2563eb
   */
  ctaButtonColor?: string | null;
  isDefault?: boolean | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages".
 */
export interface Page {
  id: number;
  title: string;
  slug: string;
  content?: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  } | null;
  isActive?: boolean | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews".
 */
export interface Review {
  id: number;
  author: string;
  /**
   * Ukryty, nie wyświetlany publicznie
   */
  email?: string | null;
  operator: number | Operator;
  plan?: (number | null) | Plan;
  city?: (number | null) | City;
  rating: number;
  title: string;
  content: string;
  pros?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  cons?:
    | {
        text: string;
        id?: string | null;
      }[]
    | null;
  /**
   * Potwierdzona opinia (np. od klienta)
   */
  isVerified?: boolean | null;
  /**
   * Moderacja — widoczna publicznie po zatwierdzeniu
   */
  isApproved?: boolean | null;
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts".
 */
export interface BlogPost {
  id: number;
  title: string;
  slug: string;
  /**
   * Krótki opis do listy artykułów i meta description
   */
  excerpt?: string | null;
  content: {
    root: {
      type: string;
      children: {
        type: any;
        version: number;
        [k: string]: unknown;
      }[];
      direction: ('ltr' | 'rtl') | null;
      format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
      indent: number;
      version: number;
    };
    [k: string]: unknown;
  };
  featuredImage?: (number | null) | Media;
  author?: (number | null) | User;
  categories?: (number | BlogCategory)[] | null;
  tags?:
    | {
        tag: string;
        id?: string | null;
      }[]
    | null;
  relatedOperators?: (number | Operator)[] | null;
  relatedPlans?: (number | Plan)[] | null;
  status: 'draft' | 'published' | 'archived';
  publishedAt?: string | null;
  seo?: {
    metaTitle?: string | null;
    metaDescription?: string | null;
    ogImage?: (number | null) | Media;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories".
 */
export interface BlogCategory {
  id: number;
  name: string;
  /**
   * URL-friendly identyfikator
   */
  slug: string;
  description?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speed-stats".
 */
export interface SpeedStat {
  id: number;
  city: number | City;
  operator?: (number | null) | Operator;
  /**
   * Np. 2025-Q1, 2025-Q2
   */
  period: string;
  avgDownload: number;
  avgUpload: number;
  avgLatency?: number | null;
  sampleCount?: number | null;
  source: 'ookla' | 'user-reported' | 'uke';
  dataDate?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-alerts".
 */
export interface PriceAlert {
  id: number;
  email: string;
  city?: (number | null) | City;
  category?: (number | null) | Category;
  /**
   * Powiadom gdy pojawi się oferta poniżej tej ceny
   */
  maxPrice?: number | null;
  /**
   * Powiadom gdy pojawi się oferta z prędkością >= tej wartości
   */
  minSpeed?: number | null;
  operators?: (number | Operator)[] | null;
  isActive?: boolean | null;
  lastNotified?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons".
 */
export interface Comparison {
  id: number;
  /**
   * Unikalny identyfikator sesji użytkownika
   */
  sessionId: string;
  plans: (number | Plan)[];
  ipHash?: string | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily".
 */
export interface AnalyticsDaily {
  id: number;
  date: string;
  operator?: (number | null) | Operator;
  plan?: (number | null) | Plan;
  city?: (number | null) | City;
  clicks?: number | null;
  impressions?: number | null;
  redirects?: number | null;
  conversions?: number | null;
  /**
   * Click-through rate = clicks/impressions * 100
   */
  ctr?: number | null;
  revenue?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv".
 */
export interface PayloadKv {
  id: number;
  key: string;
  data:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents".
 */
export interface PayloadLockedDocument {
  id: number;
  document?:
    | ({
        relationTo: 'users';
        value: number | User;
      } | null)
    | ({
        relationTo: 'media';
        value: number | Media;
      } | null)
    | ({
        relationTo: 'operators';
        value: number | Operator;
      } | null)
    | ({
        relationTo: 'plans';
        value: number | Plan;
      } | null)
    | ({
        relationTo: 'categories';
        value: number | Category;
      } | null)
    | ({
        relationTo: 'cities';
        value: number | City;
      } | null)
    | ({
        relationTo: 'city-landing-pages';
        value: number | CityLandingPage;
      } | null)
    | ({
        relationTo: 'promotions';
        value: number | Promotion;
      } | null)
    | ({
        relationTo: 'click-events';
        value: number | ClickEvent;
      } | null)
    | ({
        relationTo: 'affiliate-links';
        value: number | AffiliateLink;
      } | null)
    | ({
        relationTo: 'box-display-config';
        value: number | BoxDisplayConfig;
      } | null)
    | ({
        relationTo: 'pages';
        value: number | Page;
      } | null)
    | ({
        relationTo: 'reviews';
        value: number | Review;
      } | null)
    | ({
        relationTo: 'blog-posts';
        value: number | BlogPost;
      } | null)
    | ({
        relationTo: 'blog-categories';
        value: number | BlogCategory;
      } | null)
    | ({
        relationTo: 'speed-stats';
        value: number | SpeedStat;
      } | null)
    | ({
        relationTo: 'price-alerts';
        value: number | PriceAlert;
      } | null)
    | ({
        relationTo: 'comparisons';
        value: number | Comparison;
      } | null)
    | ({
        relationTo: 'analytics-daily';
        value: number | AnalyticsDaily;
      } | null);
  globalSlug?: string | null;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences".
 */
export interface PayloadPreference {
  id: number;
  user: {
    relationTo: 'users';
    value: number | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations".
 */
export interface PayloadMigration {
  id: number;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "users_select".
 */
export interface UsersSelect<T extends boolean = true> {
  firstName?: T;
  lastName?: T;
  role?: T;
  updatedAt?: T;
  createdAt?: T;
  email?: T;
  resetPasswordToken?: T;
  resetPasswordExpiration?: T;
  salt?: T;
  hash?: T;
  loginAttempts?: T;
  lockUntil?: T;
  sessions?:
    | T
    | {
        id?: T;
        createdAt?: T;
        expiresAt?: T;
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "media_select".
 */
export interface MediaSelect<T extends boolean = true> {
  alt?: T;
  updatedAt?: T;
  createdAt?: T;
  url?: T;
  thumbnailURL?: T;
  filename?: T;
  mimeType?: T;
  filesize?: T;
  width?: T;
  height?: T;
  focalX?: T;
  focalY?: T;
  sizes?:
    | T
    | {
        thumbnail?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        card?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        banner?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
        og?:
          | T
          | {
              url?: T;
              width?: T;
              height?: T;
              mimeType?: T;
              filesize?: T;
              filename?: T;
            };
      };
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "operators_select".
 */
export interface OperatorsSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  logo?: T;
  logoDark?: T;
  description?: T;
  shortDescription?: T;
  website?: T;
  supportPhone?: T;
  coverageMapUrl?: T;
  rating?: T;
  reviewCount?: T;
  isActive?: T;
  isPremiumPartner?: T;
  priority?: T;
  commission?:
    | T
    | {
        type?: T;
        value?: T;
      };
  contact?:
    | T
    | {
        person?: T;
        email?: T;
        phone?: T;
        notes?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "plans_select".
 */
export interface PlansSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  operator?: T;
  category?: T;
  technology?: T;
  speeds?:
    | T
    | {
        download?: T;
        upload?: T;
        guaranteed?: T;
      };
  pricing?:
    | T
    | {
        priceMonthly?: T;
        pricePromo?: T;
        promoMonths?: T;
        priceAfterPromo?: T;
        installationFee?: T;
        activationFee?: T;
        totalCost24m?: T;
      };
  contract?:
    | T
    | {
        months?: T;
        cancellationFee?: T;
        freeRouterIncluded?: T;
        routerModel?: T;
      };
  extras?:
    | T
    | {
        includesTV?: T;
        tvChannels?: T;
        includesPhone?: T;
        includesMobile?: T;
        features?:
          | T
          | {
              feature?: T;
              id?: T;
            };
        additionalInfo?: T;
      };
  display?:
    | T
    | {
        badge?: T;
        badgeColor?: T;
        highlightBox?: T;
        customCTA?: T;
        sortOrder?: T;
      };
  affiliate?:
    | T
    | {
        url?: T;
        affiliateId?: T;
        landingPageUrl?: T;
      };
  sponsoring?:
    | T
    | {
        isSponsored?: T;
        sponsoredLabel?: T;
        sponsoredFrom?: T;
        sponsoredUntil?: T;
      };
  availability?:
    | T
    | {
        isActive?: T;
        isPromoted?: T;
        regions?: T;
        validFrom?: T;
        validUntil?: T;
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "categories_select".
 */
export interface CategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  urlPrefix?: T;
  icon?: T;
  description?: T;
  shortDescription?: T;
  sortOrder?: T;
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        h1Template?: T;
        contentTemplate?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "cities_select".
 */
export interface CitiesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  voivodeship?: T;
  population?: T;
  isMainCity?: T;
  availableOperators?: T;
  coordinates?:
    | T
    | {
        lat?: T;
        lng?: T;
      };
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "city-landing-pages_select".
 */
export interface CityLandingPagesSelect<T extends boolean = true> {
  title?: T;
  city?: T;
  category?: T;
  slug?: T;
  content?:
    | T
    | {
        h1?: T;
        heroText?: T;
        bodyContent?: T;
        faqItems?:
          | T
          | {
              question?: T;
              answer?: T;
              id?: T;
            };
        ctaText?: T;
      };
  featured?:
    | T
    | {
        operators?: T;
        plans?: T;
        customSortOrder?:
          | T
          | {
              operator?: T;
              position?: T;
              id?: T;
            };
      };
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        canonicalUrl?: T;
        ogImage?: T;
      };
  isActive?: T;
  publishedAt?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "promotions_select".
 */
export interface PromotionsSelect<T extends boolean = true> {
  name?: T;
  type?: T;
  placement?: T;
  operator?: T;
  plan?: T;
  image?: T;
  imageMobile?: T;
  title?: T;
  description?: T;
  ctaText?: T;
  ctaUrl?: T;
  affiliateUrl?: T;
  backgroundColor?: T;
  isActive?: T;
  startDate?: T;
  endDate?: T;
  impressionLimit?: T;
  impressionCount?: T;
  priority?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "click-events_select".
 */
export interface ClickEventsSelect<T extends boolean = true> {
  plan?: T;
  operator?: T;
  promotion?: T;
  eventType?: T;
  sourceUrl?: T;
  destinationUrl?: T;
  userAgent?: T;
  ipHash?: T;
  referrer?: T;
  utm?:
    | T
    | {
        source?: T;
        medium?: T;
        campaign?: T;
        term?: T;
        content?: T;
      };
  device?:
    | T
    | {
        type?: T;
        browser?: T;
        os?: T;
      };
  city?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "affiliate-links_select".
 */
export interface AffiliateLinksSelect<T extends boolean = true> {
  name?: T;
  operator?: T;
  baseUrl?: T;
  trackingParam?: T;
  trackingId?: T;
  additionalParams?:
    | T
    | {
        key?: T;
        value?: T;
        id?: T;
      };
  isActive?: T;
  cookieDays?: T;
  commissionType?: T;
  commissionRate?: T;
  notes?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "box-display-config_select".
 */
export interface BoxDisplayConfigSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  layout?: T;
  visibleFields?:
    | T
    | {
        fieldName?: T;
        label?: T;
        displayOrder?: T;
        showOnMobile?: T;
        id?: T;
      };
  showOperatorLogo?: T;
  showBadge?: T;
  showRating?: T;
  showSponsored?: T;
  ctaButtonText?: T;
  ctaButtonColor?: T;
  isDefault?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "pages_select".
 */
export interface PagesSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  content?: T;
  isActive?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "reviews_select".
 */
export interface ReviewsSelect<T extends boolean = true> {
  author?: T;
  email?: T;
  operator?: T;
  plan?: T;
  city?: T;
  rating?: T;
  title?: T;
  content?: T;
  pros?:
    | T
    | {
        text?: T;
        id?: T;
      };
  cons?:
    | T
    | {
        text?: T;
        id?: T;
      };
  isVerified?: T;
  isApproved?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-posts_select".
 */
export interface BlogPostsSelect<T extends boolean = true> {
  title?: T;
  slug?: T;
  excerpt?: T;
  content?: T;
  featuredImage?: T;
  author?: T;
  categories?: T;
  tags?:
    | T
    | {
        tag?: T;
        id?: T;
      };
  relatedOperators?: T;
  relatedPlans?: T;
  status?: T;
  publishedAt?: T;
  seo?:
    | T
    | {
        metaTitle?: T;
        metaDescription?: T;
        ogImage?: T;
      };
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "blog-categories_select".
 */
export interface BlogCategoriesSelect<T extends boolean = true> {
  name?: T;
  slug?: T;
  description?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "speed-stats_select".
 */
export interface SpeedStatsSelect<T extends boolean = true> {
  city?: T;
  operator?: T;
  period?: T;
  avgDownload?: T;
  avgUpload?: T;
  avgLatency?: T;
  sampleCount?: T;
  source?: T;
  dataDate?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "price-alerts_select".
 */
export interface PriceAlertsSelect<T extends boolean = true> {
  email?: T;
  city?: T;
  category?: T;
  maxPrice?: T;
  minSpeed?: T;
  operators?: T;
  isActive?: T;
  lastNotified?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparisons_select".
 */
export interface ComparisonsSelect<T extends boolean = true> {
  sessionId?: T;
  plans?: T;
  ipHash?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "analytics-daily_select".
 */
export interface AnalyticsDailySelect<T extends boolean = true> {
  date?: T;
  operator?: T;
  plan?: T;
  city?: T;
  clicks?: T;
  impressions?: T;
  redirects?: T;
  conversions?: T;
  ctr?: T;
  revenue?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-kv_select".
 */
export interface PayloadKvSelect<T extends boolean = true> {
  key?: T;
  data?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-locked-documents_select".
 */
export interface PayloadLockedDocumentsSelect<T extends boolean = true> {
  document?: T;
  globalSlug?: T;
  user?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-preferences_select".
 */
export interface PayloadPreferencesSelect<T extends boolean = true> {
  user?: T;
  key?: T;
  value?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "payload-migrations_select".
 */
export interface PayloadMigrationsSelect<T extends boolean = true> {
  name?: T;
  batch?: T;
  updatedAt?: T;
  createdAt?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings".
 */
export interface SiteSetting {
  id: number;
  siteName: string;
  siteDescription?: string | null;
  defaultLanguage?: ('pl' | 'en') | null;
  contactEmail?: string | null;
  socialLinks?: {
    facebook?: string | null;
    twitter?: string | null;
    instagram?: string | null;
    linkedin?: string | null;
  };
  analytics?: {
    /**
     * np. G-XXXXXXXXXX
     */
    googleAnalyticsId?: string | null;
    googleTagManagerId?: string | null;
  };
  cookieConsentText?: string | null;
  footer?: {
    text?: {
      root: {
        type: string;
        children: {
          type: any;
          version: number;
          [k: string]: unknown;
        }[];
        direction: ('ltr' | 'rtl') | null;
        format: 'left' | 'start' | 'center' | 'right' | 'end' | 'justify' | '';
        indent: number;
        version: number;
      };
      [k: string]: unknown;
    } | null;
    copyrightText?: string | null;
  };
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-config".
 */
export interface ComparisonConfig {
  id: number;
  defaultSortBy?: ('price' | 'speed' | 'rating' | 'promoted' | 'priority') | null;
  resultsPerPage?: number | null;
  /**
   * Oferty sponsorowane zawsze wyświetlane jako pierwsze
   */
  showSponsoredFirst?: boolean | null;
  defaultCategory?: (number | null) | Category;
  enableClickTracking?: boolean | null;
  defaultBoxConfig?: (number | null) | BoxDisplayConfig;
  availableFilters?: {
    showCategoryFilter?: boolean | null;
    showSpeedFilter?: boolean | null;
    showPriceFilter?: boolean | null;
    showOperatorFilter?: boolean | null;
    showContractFilter?: boolean | null;
    showTechnologyFilter?: boolean | null;
    showCityFilter?: boolean | null;
  };
  speedRanges?:
    | {
        label: string;
        /**
         * np. "100mb", "300mb", "1gb"
         */
        slug: string;
        minSpeed: number;
        /**
         * Puste = bez limitu
         */
        maxSpeed?: number | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation".
 */
export interface Navigation {
  id: number;
  mainMenu?:
    | {
        label: string;
        url: string;
        isExternal?: boolean | null;
        openInNewTab?: boolean | null;
        children?:
          | {
              label: string;
              url: string;
              isExternal?: boolean | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  footerMenu?:
    | {
        columnTitle: string;
        links?:
          | {
              label: string;
              url: string;
              isExternal?: boolean | null;
              openInNewTab?: boolean | null;
              id?: string | null;
            }[]
          | null;
        id?: string | null;
      }[]
    | null;
  /**
   * Jeśli puste, używa menu głównego
   */
  mobileMenu?:
    | {
        label: string;
        url: string;
        isExternal?: boolean | null;
        openInNewTab?: boolean | null;
        id?: string | null;
      }[]
    | null;
  updatedAt?: string | null;
  createdAt?: string | null;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "site-settings_select".
 */
export interface SiteSettingsSelect<T extends boolean = true> {
  siteName?: T;
  siteDescription?: T;
  defaultLanguage?: T;
  contactEmail?: T;
  socialLinks?:
    | T
    | {
        facebook?: T;
        twitter?: T;
        instagram?: T;
        linkedin?: T;
      };
  analytics?:
    | T
    | {
        googleAnalyticsId?: T;
        googleTagManagerId?: T;
      };
  cookieConsentText?: T;
  footer?:
    | T
    | {
        text?: T;
        copyrightText?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "comparison-config_select".
 */
export interface ComparisonConfigSelect<T extends boolean = true> {
  defaultSortBy?: T;
  resultsPerPage?: T;
  showSponsoredFirst?: T;
  defaultCategory?: T;
  enableClickTracking?: T;
  defaultBoxConfig?: T;
  availableFilters?:
    | T
    | {
        showCategoryFilter?: T;
        showSpeedFilter?: T;
        showPriceFilter?: T;
        showOperatorFilter?: T;
        showContractFilter?: T;
        showTechnologyFilter?: T;
        showCityFilter?: T;
      };
  speedRanges?:
    | T
    | {
        label?: T;
        slug?: T;
        minSpeed?: T;
        maxSpeed?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "navigation_select".
 */
export interface NavigationSelect<T extends boolean = true> {
  mainMenu?:
    | T
    | {
        label?: T;
        url?: T;
        isExternal?: T;
        openInNewTab?: T;
        children?:
          | T
          | {
              label?: T;
              url?: T;
              isExternal?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  footerMenu?:
    | T
    | {
        columnTitle?: T;
        links?:
          | T
          | {
              label?: T;
              url?: T;
              isExternal?: T;
              openInNewTab?: T;
              id?: T;
            };
        id?: T;
      };
  mobileMenu?:
    | T
    | {
        label?: T;
        url?: T;
        isExternal?: T;
        openInNewTab?: T;
        id?: T;
      };
  updatedAt?: T;
  createdAt?: T;
  globalType?: T;
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "collections_widget".
 */
export interface CollectionsWidget {
  data?: {
    [k: string]: unknown;
  };
  width: 'full';
}
/**
 * This interface was referenced by `Config`'s JSON-Schema
 * via the `definition` "auth".
 */
export interface Auth {
  [k: string]: unknown;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}